### ISSUE TITLE
Collected description formatting missing spaces

### ISSUE THREAD

**Issue by 03y** [henriupton99/AdventOfCode#1]
When collecting the problem desciption today (1 2024), there's a lot of spaces missing:

```
Within each pair, figure outhow far apartthe two numbers are; you'll need toadd up all of those distances. For example, if you pair up a3from the left list with a7from the right list, the distance apart is4; if you pair up a9with a3, the distance apart is6.
```

Thank you for this tool!

**Comment by henriupton99** [comment]
The problem came from the argument "strip" set to True in the .get_text() method in the [daily_collect.py](https://github.com/henriupton99/AdventOfCode/blob/main/templates/daily_collect.py) 

An example for the first paragraph, day 11 of year 2022 : 
- With strip == True : "As you finally start making your way upriver, you realize your pack is much lighter than you remember. Just then, one of the items from your pack goes flying overhead. Monkeys are **playing Keep** Away with your missing things!"
- With strip == False: "As you finally start making your way upriver, you realize your pack is much lighter than you remember. Just then, one of the items from your pack goes flying overhead. Monkeys are **playingKeep** **Awaywith** your missing things!"

Corrected then by removing "strip=True" in the day description collection section.
